title: Moonss
description: 머신러닝에 입문하는 주니어 개발자 
author: jaeyun
avatar: /assets/image/profil.png
email: mjy2256@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: jaeyun
  card: summary
logo: /assets/image/profil.png
social:
  name: jaeyun
  links:
    - https://www.facebook.com/jaeyun.moon.5/
    - https://github.com/Moonss-0913
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
